# Generated by Django 2.2.1 on 2019-11-03 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuetracker', '0004_auto_20191010_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(auto_now=True, verbose_name='Finished at')),
                ('project_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_project', to='issuetracker.Project', verbose_name='Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_member', to=settings.AUTH_USER_MODEL, verbose_name='Users in team')),
            ],
        ),
    ]
