# Generated by Django 2.2.1 on 2019-11-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='finished_at',
            field=models.DateField(verbose_name='Finished at'),
        ),
    ]
