# Generated by Django 2.2.1 on 2019-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_auto_20191104_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='finished_at',
            field=models.DateTimeField(verbose_name='Finished at'),
        ),
    ]
