# Generated by Django 2.2.1 on 2019-11-05 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import issuetracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0010_auto_20191105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=issuetracker.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
