# Generated by Django 2.2.1 on 2019-11-07 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0011_auto_20191105_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_project', to='issuetracker.Project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_user', to=settings.AUTH_USER_MODEL, verbose_name='Users in team'),
        ),
    ]
