# Generated by Django 2.2.1 on 2019-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0012_auto_20191107_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Finished at'),
        ),
    ]
