# Generated by Django 2.2.1 on 2019-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0013_auto_20191107_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Started at'),
        ),
    ]
