# Generated by Django 2.2.1 on 2019-11-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
