# Generated by Django 2.2.1 on 2019-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlink_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlink',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
